export const productItems = [
  {
    id: 1,
    name: "상품 A",
    category: "living",
    scope: "5.0",
    amount: "15,000",
    likeCount: 0,
  },
  {
    id: 2,
    name: "상품 B",
    category: "sporting",
    scope: "4.5",
    amount: "10,000",
    likeCount: 0,
  },
  {
    id: 3,
    name: "상품 C",
    category: "living",
    scope: "4.5",
    amount: "56,000",
    likeCount: 0,
  },
  {
    id: 4,
    name: "상품 D",
    category: "apparel",
    scope: "5.0",
    amount: "43,000",
    likeCount: 0,
  },
  {
    id: 5,
    name: "상품 E",
    category: "sporting",
    scope: "4.3",
    amount: "11,000",
    likeCount: 0,
  },
  {
    id: 6,
    name: "상품 F",
    category: "living",
    scope: "5.0",
    amount: "5,000",
    likeCount: 0,
  },
  {
    id: 7,
    name: "상품 G",
    category: "apparel",
    scope: "4.3",
    amount: "10,000",
    likeCount: 0,
  },
  {
    id: 8,
    name: "상품 H",
    category: "sporting",
    scope: "3.8",
    amount: "32,000",
    likeCount: 0,
  },
  {
    id: 9,
    name: "상품 I",
    category: "electronic",
    scope: "4.5",
    amount: "78,000",
    likeCount: 0,
  },
  {
    id: 10,
    name: "상품 J",
    category: "living",
    scope: "5.0",
    amount: "15,000",
    likeCount: 0,
  },
  {
    id: 11,
    name: "상품 K",
    category: "electronic",
    scope: "3.5",
    amount: "112,000",
    likeCount: 0,
  },
];